# Generated by Django 4.0.5 on 2022-06-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=60, null=True)),
                ('price', models.CharField(max_length=60, null=True)),
                ('image', models.URLField(blank=True, max_length=250, null=True)),
                ('temperature', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(max_length=60, null=True)),
                ('email', models.CharField(max_length=60, null=True)),
                ('password', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
